// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pckt/openapi/annotations.proto

//go:build protoopaque

package openapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_pckt_openapi_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         60200,
		Name:          "pckt.openapi.field",
		Tag:           "bytes,60200,opt,name=field",
		Filename:      "pckt/openapi/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*SchemaOptions)(nil),
		Field:         60201,
		Name:          "pckt.openapi.schema",
		Tag:           "bytes,60201,opt,name=schema",
		Filename:      "pckt/openapi/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*OperationOptions)(nil),
		Field:         60202,
		Name:          "pckt.openapi.operation",
		Tag:           "bytes,60202,opt,name=operation",
		Filename:      "pckt/openapi/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*TagOptions)(nil),
		Field:         60203,
		Name:          "pckt.openapi.tag",
		Tag:           "bytes,60203,opt,name=tag",
		Filename:      "pckt/openapi/annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional pckt.openapi.FieldOptions field = 60200;
	E_Field = &file_pckt_openapi_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional pckt.openapi.SchemaOptions schema = 60201;
	E_Schema = &file_pckt_openapi_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional pckt.openapi.OperationOptions operation = 60202;
	E_Operation = &file_pckt_openapi_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional pckt.openapi.TagOptions tag = 60203;
	E_Tag = &file_pckt_openapi_annotations_proto_extTypes[3]
)

var File_pckt_openapi_annotations_proto protoreflect.FileDescriptor

const file_pckt_openapi_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1epckt/openapi/annotations.proto\x12\fpckt.openapi\x1a google/protobuf/descriptor.proto\x1a\x1apckt/openapi/options.proto:Q\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xa8\xd6\x03 \x01(\v2\x1a.pckt.openapi.FieldOptionsR\x05field:V\n" +
	"\x06schema\x12\x1f.google.protobuf.MessageOptions\x18\xa9\xd6\x03 \x01(\v2\x1b.pckt.openapi.SchemaOptionsR\x06schema:^\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xaa\xd6\x03 \x01(\v2\x1e.pckt.openapi.OperationOptionsR\toperation:M\n" +
	"\x03tag\x12\x1f.google.protobuf.ServiceOptions\x18\xab\xd6\x03 \x01(\v2\x18.pckt.openapi.TagOptionsR\x03tagB/Z-github.com/pckt-sh/openapi/proto/pckt/openapib\x06proto3"

var file_pckt_openapi_annotations_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),   // 0: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
	(*FieldOptions)(nil),                // 4: pckt.openapi.FieldOptions
	(*SchemaOptions)(nil),               // 5: pckt.openapi.SchemaOptions
	(*OperationOptions)(nil),            // 6: pckt.openapi.OperationOptions
	(*TagOptions)(nil),                  // 7: pckt.openapi.TagOptions
}
var file_pckt_openapi_annotations_proto_depIdxs = []int32{
	0, // 0: pckt.openapi.field:extendee -> google.protobuf.FieldOptions
	1, // 1: pckt.openapi.schema:extendee -> google.protobuf.MessageOptions
	2, // 2: pckt.openapi.operation:extendee -> google.protobuf.MethodOptions
	3, // 3: pckt.openapi.tag:extendee -> google.protobuf.ServiceOptions
	4, // 4: pckt.openapi.field:type_name -> pckt.openapi.FieldOptions
	5, // 5: pckt.openapi.schema:type_name -> pckt.openapi.SchemaOptions
	6, // 6: pckt.openapi.operation:type_name -> pckt.openapi.OperationOptions
	7, // 7: pckt.openapi.tag:type_name -> pckt.openapi.TagOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	4, // [4:8] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pckt_openapi_annotations_proto_init() }
func file_pckt_openapi_annotations_proto_init() {
	if File_pckt_openapi_annotations_proto != nil {
		return
	}
	file_pckt_openapi_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pckt_openapi_annotations_proto_rawDesc), len(file_pckt_openapi_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_pckt_openapi_annotations_proto_goTypes,
		DependencyIndexes: file_pckt_openapi_annotations_proto_depIdxs,
		ExtensionInfos:    file_pckt_openapi_annotations_proto_extTypes,
	}.Build()
	File_pckt_openapi_annotations_proto = out.File
	file_pckt_openapi_annotations_proto_goTypes = nil
	file_pckt_openapi_annotations_proto_depIdxs = nil
}
