// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pckt/openapi/options.proto

//go:build !protoopaque

package openapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	// Number
	FieldType_FIELD_TYPE_FLOAT  FieldType = 1
	FieldType_FIELD_TYPE_DOUBLE FieldType = 2
	FieldType_FIELD_TYPE_INT32  FieldType = 3
	FieldType_FIELD_TYPE_INT64  FieldType = 4
	// Array
	FieldType_FIELD_TYPE_ARRAY FieldType = 5
	// Object
	FieldType_FIELD_TYPE_OBJECT FieldType = 6
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_FLOAT",
		2: "FIELD_TYPE_DOUBLE",
		3: "FIELD_TYPE_INT32",
		4: "FIELD_TYPE_INT64",
		5: "FIELD_TYPE_ARRAY",
		6: "FIELD_TYPE_OBJECT",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_FLOAT":       1,
		"FIELD_TYPE_DOUBLE":      2,
		"FIELD_TYPE_INT32":       3,
		"FIELD_TYPE_INT64":       4,
		"FIELD_TYPE_ARRAY":       5,
		"FIELD_TYPE_OBJECT":      6,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_pckt_openapi_options_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_pckt_openapi_options_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FieldFormat int32

const (
	FieldFormat_FIELD_FORMAT_UNSPECIFIED FieldFormat = 0
	// Date and times
	FieldFormat_FIELD_FORMAT_DATE_TIME FieldFormat = 1
	FieldFormat_FIELD_FORMAT_TIME      FieldFormat = 2
	FieldFormat_FIELD_FORMAT_DATE      FieldFormat = 3
	FieldFormat_FIELD_FORMAT_DURATION  FieldFormat = 4
	// Email addresses
	FieldFormat_FIELD_FORMAT_EMAIL     FieldFormat = 100
	FieldFormat_FIELD_FORMAT_IDN_EMAIL FieldFormat = 101
	// Hostnames
	FieldFormat_FIELD_FORMAT_HOSTNAME     FieldFormat = 200
	FieldFormat_FIELD_FORMAT_IDN_HOSTNAME FieldFormat = 201
	// IP addresses
	FieldFormat_FIELD_FORMAT_IPV4 FieldFormat = 300
	FieldFormat_FIELD_FORMAT_IPV6 FieldFormat = 301
	// Resource identifiers
	FieldFormat_FIELD_FORMAT_UUID          FieldFormat = 400
	FieldFormat_FIELD_FORMAT_URI           FieldFormat = 401
	FieldFormat_FIELD_FORMAT_URI_REFERENCE FieldFormat = 402
	FieldFormat_FIELD_FORMAT_IRI           FieldFormat = 403
	FieldFormat_FIELD_FORMAT_IRI_REFERENCE FieldFormat = 404
	// URI template
	FieldFormat_FIELD_FORMAT_URI_TEMPLATE FieldFormat = 500
	// JSON pointer
	FieldFormat_FIELD_FORMAT_JSON_POINTER          FieldFormat = 600
	FieldFormat_FIELD_FORMAT_RELATIVE_JSON_POINTER FieldFormat = 601
	// Regex
	FieldFormat_FIELD_FORMAT_REGEX FieldFormat = 700
)

// Enum value maps for FieldFormat.
var (
	FieldFormat_name = map[int32]string{
		0:   "FIELD_FORMAT_UNSPECIFIED",
		1:   "FIELD_FORMAT_DATE_TIME",
		2:   "FIELD_FORMAT_TIME",
		3:   "FIELD_FORMAT_DATE",
		4:   "FIELD_FORMAT_DURATION",
		100: "FIELD_FORMAT_EMAIL",
		101: "FIELD_FORMAT_IDN_EMAIL",
		200: "FIELD_FORMAT_HOSTNAME",
		201: "FIELD_FORMAT_IDN_HOSTNAME",
		300: "FIELD_FORMAT_IPV4",
		301: "FIELD_FORMAT_IPV6",
		400: "FIELD_FORMAT_UUID",
		401: "FIELD_FORMAT_URI",
		402: "FIELD_FORMAT_URI_REFERENCE",
		403: "FIELD_FORMAT_IRI",
		404: "FIELD_FORMAT_IRI_REFERENCE",
		500: "FIELD_FORMAT_URI_TEMPLATE",
		600: "FIELD_FORMAT_JSON_POINTER",
		601: "FIELD_FORMAT_RELATIVE_JSON_POINTER",
		700: "FIELD_FORMAT_REGEX",
	}
	FieldFormat_value = map[string]int32{
		"FIELD_FORMAT_UNSPECIFIED":           0,
		"FIELD_FORMAT_DATE_TIME":             1,
		"FIELD_FORMAT_TIME":                  2,
		"FIELD_FORMAT_DATE":                  3,
		"FIELD_FORMAT_DURATION":              4,
		"FIELD_FORMAT_EMAIL":                 100,
		"FIELD_FORMAT_IDN_EMAIL":             101,
		"FIELD_FORMAT_HOSTNAME":              200,
		"FIELD_FORMAT_IDN_HOSTNAME":          201,
		"FIELD_FORMAT_IPV4":                  300,
		"FIELD_FORMAT_IPV6":                  301,
		"FIELD_FORMAT_UUID":                  400,
		"FIELD_FORMAT_URI":                   401,
		"FIELD_FORMAT_URI_REFERENCE":         402,
		"FIELD_FORMAT_IRI":                   403,
		"FIELD_FORMAT_IRI_REFERENCE":         404,
		"FIELD_FORMAT_URI_TEMPLATE":          500,
		"FIELD_FORMAT_JSON_POINTER":          600,
		"FIELD_FORMAT_RELATIVE_JSON_POINTER": 601,
		"FIELD_FORMAT_REGEX":                 700,
	}
)

func (x FieldFormat) Enum() *FieldFormat {
	p := new(FieldFormat)
	*p = x
	return p
}

func (x FieldFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_pckt_openapi_options_proto_enumTypes[1].Descriptor()
}

func (FieldFormat) Type() protoreflect.EnumType {
	return &file_pckt_openapi_options_proto_enumTypes[1]
}

func (x FieldFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FieldOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Value example (always in string, but casted to correct type during generation)
	Example string `protobuf:"bytes,2,opt,name=example,proto3" json:"example,omitempty"`
	// Field type, extracted from field type when empty
	Type FieldType `protobuf:"varint,3,opt,name=type,proto3,enum=pckt.openapi.FieldType" json:"type,omitempty"`
	// Well-known format, extract from field type when empty
	Format FieldFormat `protobuf:"varint,4,opt,name=format,proto3,enum=pckt.openapi.FieldFormat" json:"format,omitempty"`
	// Regex pattern
	Pattern string `protobuf:"bytes,5,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Set the field as deprecated
	Deprecated bool `protobuf:"varint,6,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// Omit the field from the generated schema
	Hidden bool `protobuf:"varint,7,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// Mark the field as required in the parent schema
	Required bool `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	// Field is only sent in responses
	ReadOnly bool `protobuf:"varint,9,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Field is only sent in requests
	WriteOnly bool `protobuf:"varint,10,opt,name=write_only,json=writeOnly,proto3" json:"write_only,omitempty"`
	// Numeric constraints
	Minimum *float64 `protobuf:"fixed64,11,opt,name=minimum,proto3,oneof" json:"minimum,omitempty"`
	Maximum *float64 `protobuf:"fixed64,12,opt,name=maximum,proto3,oneof" json:"maximum,omitempty"`
	// String length constraints
	MinLength *uint64 `protobuf:"varint,13,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength *uint64 `protobuf:"varint,14,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	// Repeated field constraints
	MinItems *uint64 `protobuf:"varint,15,opt,name=min_items,json=minItems,proto3,oneof" json:"min_items,omitempty"`
	MaxItems *uint64 `protobuf:"varint,16,opt,name=max_items,json=maxItems,proto3,oneof" json:"max_items,omitempty"`
	// OpenAPI extensions added to the field schema, keys must start with `x-`
	Extensions    map[string]*structpb.Value `protobuf:"bytes,17,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_pckt_openapi_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pckt_openapi_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldOptions) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *FieldOptions) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *FieldOptions) GetFormat() FieldFormat {
	if x != nil {
		return x.Format
	}
	return FieldFormat_FIELD_FORMAT_UNSPECIFIED
}

func (x *FieldOptions) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FieldOptions) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *FieldOptions) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *FieldOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldOptions) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *FieldOptions) GetWriteOnly() bool {
	if x != nil {
		return x.WriteOnly
	}
	return false
}

func (x *FieldOptions) GetMinimum() float64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	return 0
}

func (x *FieldOptions) GetMaximum() float64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	return 0
}

func (x *FieldOptions) GetMinLength() uint64 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *FieldOptions) GetMaxLength() uint64 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *FieldOptions) GetMinItems() uint64 {
	if x != nil && x.MinItems != nil {
		return *x.MinItems
	}
	return 0
}

func (x *FieldOptions) GetMaxItems() uint64 {
	if x != nil && x.MaxItems != nil {
		return *x.MaxItems
	}
	return 0
}

func (x *FieldOptions) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *FieldOptions) SetExample(v string) {
	x.Example = v
}

func (x *FieldOptions) SetType(v FieldType) {
	x.Type = v
}

func (x *FieldOptions) SetFormat(v FieldFormat) {
	x.Format = v
}

func (x *FieldOptions) SetPattern(v string) {
	x.Pattern = v
}

func (x *FieldOptions) SetDeprecated(v bool) {
	x.Deprecated = v
}

func (x *FieldOptions) SetHidden(v bool) {
	x.Hidden = v
}

func (x *FieldOptions) SetRequired(v bool) {
	x.Required = v
}

func (x *FieldOptions) SetReadOnly(v bool) {
	x.ReadOnly = v
}

func (x *FieldOptions) SetWriteOnly(v bool) {
	x.WriteOnly = v
}

func (x *FieldOptions) SetMinimum(v float64) {
	x.Minimum = &v
}

func (x *FieldOptions) SetMaximum(v float64) {
	x.Maximum = &v
}

func (x *FieldOptions) SetMinLength(v uint64) {
	x.MinLength = &v
}

func (x *FieldOptions) SetMaxLength(v uint64) {
	x.MaxLength = &v
}

func (x *FieldOptions) SetMinItems(v uint64) {
	x.MinItems = &v
}

func (x *FieldOptions) SetMaxItems(v uint64) {
	x.MaxItems = &v
}

func (x *FieldOptions) SetExtensions(v map[string]*structpb.Value) {
	x.Extensions = v
}

func (x *FieldOptions) HasMinimum() bool {
	if x == nil {
		return false
	}
	return x.Minimum != nil
}

func (x *FieldOptions) HasMaximum() bool {
	if x == nil {
		return false
	}
	return x.Maximum != nil
}

func (x *FieldOptions) HasMinLength() bool {
	if x == nil {
		return false
	}
	return x.MinLength != nil
}

func (x *FieldOptions) HasMaxLength() bool {
	if x == nil {
		return false
	}
	return x.MaxLength != nil
}

func (x *FieldOptions) HasMinItems() bool {
	if x == nil {
		return false
	}
	return x.MinItems != nil
}

func (x *FieldOptions) HasMaxItems() bool {
	if x == nil {
		return false
	}
	return x.MaxItems != nil
}

func (x *FieldOptions) ClearMinimum() {
	x.Minimum = nil
}

func (x *FieldOptions) ClearMaximum() {
	x.Maximum = nil
}

func (x *FieldOptions) ClearMinLength() {
	x.MinLength = nil
}

func (x *FieldOptions) ClearMaxLength() {
	x.MaxLength = nil
}

func (x *FieldOptions) ClearMinItems() {
	x.MinItems = nil
}

func (x *FieldOptions) ClearMaxItems() {
	x.MaxItems = nil
}

type FieldOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Value example (always in string, but casted to correct type during generation)
	Example string
	// Field type, extracted from field type when empty
	Type FieldType
	// Well-known format, extract from field type when empty
	Format FieldFormat
	// Regex pattern
	Pattern string
	// Set the field as deprecated
	Deprecated bool
	// Omit the field from the generated schema
	Hidden bool
	// Mark the field as required in the parent schema
	Required bool
	// Field is only sent in responses
	ReadOnly bool
	// Field is only sent in requests
	WriteOnly bool
	// Numeric constraints
	Minimum *float64
	Maximum *float64
	// String length constraints
	MinLength *uint64
	MaxLength *uint64
	// Repeated field constraints
	MinItems *uint64
	MaxItems *uint64
	// OpenAPI extensions added to the field schema, keys must start with `x-`
	Extensions map[string]*structpb.Value
}

func (b0 FieldOptions_builder) Build() *FieldOptions {
	m0 := &FieldOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Example = b.Example
	x.Type = b.Type
	x.Format = b.Format
	x.Pattern = b.Pattern
	x.Deprecated = b.Deprecated
	x.Hidden = b.Hidden
	x.Required = b.Required
	x.ReadOnly = b.ReadOnly
	x.WriteOnly = b.WriteOnly
	x.Minimum = b.Minimum
	x.Maximum = b.Maximum
	x.MinLength = b.MinLength
	x.MaxLength = b.MaxLength
	x.MinItems = b.MinItems
	x.MaxItems = b.MaxItems
	x.Extensions = b.Extensions
	return m0
}

type SchemaOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Schema title
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// The schema type, very likely `object`
	Type FieldType `protobuf:"varint,3,opt,name=type,proto3,enum=pckt.openapi.FieldType" json:"type,omitempty"`
	// Omit the message from the generated schemas, fields referencing it are omitted too
	Hidden bool `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// Example of the whole message, as JSON
	Example string `protobuf:"bytes,5,opt,name=example,proto3" json:"example,omitempty"`
	// Set the schema as deprecated
	Deprecated bool `protobuf:"varint,6,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// OpenAPI extensions added to the message schema, keys must start with `x-`
	Extensions    map[string]*structpb.Value `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaOptions) Reset() {
	*x = SchemaOptions{}
	mi := &file_pckt_openapi_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaOptions) ProtoMessage() {}

func (x *SchemaOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pckt_openapi_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SchemaOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SchemaOptions) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *SchemaOptions) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *SchemaOptions) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *SchemaOptions) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *SchemaOptions) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *SchemaOptions) SetTitle(v string) {
	x.Title = v
}

func (x *SchemaOptions) SetType(v FieldType) {
	x.Type = v
}

func (x *SchemaOptions) SetHidden(v bool) {
	x.Hidden = v
}

func (x *SchemaOptions) SetExample(v string) {
	x.Example = v
}

func (x *SchemaOptions) SetDeprecated(v bool) {
	x.Deprecated = v
}

func (x *SchemaOptions) SetExtensions(v map[string]*structpb.Value) {
	x.Extensions = v
}

type SchemaOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Schema title
	Title string
	// The schema type, very likely `object`
	Type FieldType
	// Omit the message from the generated schemas, fields referencing it are omitted too
	Hidden bool
	// Example of the whole message, as JSON
	Example string
	// Set the schema as deprecated
	Deprecated bool
	// OpenAPI extensions added to the message schema, keys must start with `x-`
	Extensions map[string]*structpb.Value
}

func (b0 SchemaOptions_builder) Build() *SchemaOptions {
	m0 := &SchemaOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Title = b.Title
	x.Type = b.Type
	x.Hidden = b.Hidden
	x.Example = b.Example
	x.Deprecated = b.Deprecated
	x.Extensions = b.Extensions
	return m0
}

type OperationOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Short summary; the description is always the method leading comments
	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	// Tags, defaults to the service tag
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// Operation ID, defaults to `Service_Method`
	OperationId string `protobuf:"bytes,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Set the operation as deprecated
	Deprecated bool `protobuf:"varint,5,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// Omit the operation from the generated document
	Hidden bool `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// OpenAPI extensions added to the operation, keys must start with `x-`
	Extensions map[string]*structpb.Value `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Example of the request body, ignored for bindings without body
	RequestExample *Example `protobuf:"bytes,8,opt,name=request_example,json=requestExample,proto3" json:"request_example,omitempty"`
	// Example of the successful (200) response body
	ResponseExample *Example `protobuf:"bytes,9,opt,name=response_example,json=responseExample,proto3" json:"response_example,omitempty"`
	// Content type of the request body, defaults to `application/json`,
	// or `application/octet-stream` for google.api.HttpBody
	RequestContentType string `protobuf:"bytes,10,opt,name=request_content_type,json=requestContentType,proto3" json:"request_content_type,omitempty"`
	// Content type of the successful response, defaults to `application/json`,
	// or `application/octet-stream` for google.api.HttpBody
	ResponseContentType string `protobuf:"bytes,11,opt,name=response_content_type,json=responseContentType,proto3" json:"response_content_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OperationOptions) Reset() {
	*x = OperationOptions{}
	mi := &file_pckt_openapi_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationOptions) ProtoMessage() {}

func (x *OperationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pckt_openapi_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OperationOptions) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *OperationOptions) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *OperationOptions) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationOptions) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *OperationOptions) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *OperationOptions) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *OperationOptions) GetRequestExample() *Example {
	if x != nil {
		return x.RequestExample
	}
	return nil
}

func (x *OperationOptions) GetResponseExample() *Example {
	if x != nil {
		return x.ResponseExample
	}
	return nil
}

func (x *OperationOptions) GetRequestContentType() string {
	if x != nil {
		return x.RequestContentType
	}
	return ""
}

func (x *OperationOptions) GetResponseContentType() string {
	if x != nil {
		return x.ResponseContentType
	}
	return ""
}

func (x *OperationOptions) SetSummary(v string) {
	x.Summary = v
}

func (x *OperationOptions) SetTags(v []string) {
	x.Tags = v
}

func (x *OperationOptions) SetOperationId(v string) {
	x.OperationId = v
}

func (x *OperationOptions) SetDeprecated(v bool) {
	x.Deprecated = v
}

func (x *OperationOptions) SetHidden(v bool) {
	x.Hidden = v
}

func (x *OperationOptions) SetExtensions(v map[string]*structpb.Value) {
	x.Extensions = v
}

func (x *OperationOptions) SetRequestExample(v *Example) {
	x.RequestExample = v
}

func (x *OperationOptions) SetResponseExample(v *Example) {
	x.ResponseExample = v
}

func (x *OperationOptions) SetRequestContentType(v string) {
	x.RequestContentType = v
}

func (x *OperationOptions) SetResponseContentType(v string) {
	x.ResponseContentType = v
}

func (x *OperationOptions) HasRequestExample() bool {
	if x == nil {
		return false
	}
	return x.RequestExample != nil
}

func (x *OperationOptions) HasResponseExample() bool {
	if x == nil {
		return false
	}
	return x.ResponseExample != nil
}

func (x *OperationOptions) ClearRequestExample() {
	x.RequestExample = nil
}

func (x *OperationOptions) ClearResponseExample() {
	x.ResponseExample = nil
}

type OperationOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Short summary; the description is always the method leading comments
	Summary string
	// Tags, defaults to the service tag
	Tags []string
	// Operation ID, defaults to `Service_Method`
	OperationId string
	// Set the operation as deprecated
	Deprecated bool
	// Omit the operation from the generated document
	Hidden bool
	// OpenAPI extensions added to the operation, keys must start with `x-`
	Extensions map[string]*structpb.Value
	// Example of the request body, ignored for bindings without body
	RequestExample *Example
	// Example of the successful (200) response body
	ResponseExample *Example
	// Content type of the request body, defaults to `application/json`,
	// or `application/octet-stream` for google.api.HttpBody
	RequestContentType string
	// Content type of the successful response, defaults to `application/json`,
	// or `application/octet-stream` for google.api.HttpBody
	ResponseContentType string
}

func (b0 OperationOptions_builder) Build() *OperationOptions {
	m0 := &OperationOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Summary = b.Summary
	x.Tags = b.Tags
	x.OperationId = b.OperationId
	x.Deprecated = b.Deprecated
	x.Hidden = b.Hidden
	x.Extensions = b.Extensions
	x.RequestExample = b.RequestExample
	x.ResponseExample = b.ResponseExample
	x.RequestContentType = b.RequestContentType
	x.ResponseContentType = b.ResponseContentType
	return m0
}

// An example value. For JSON content types (`application/json`, `*+json`) the
// value is parsed as JSON, or as YAML for `.yaml` and `.yml` files; for other
// content types (e.g. google.api.HttpBody serving CSV) it is used as a string.
type Example struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*Example_Value
	//	*Example_File
	Source isExample_Source `protobuf_oneof:"source"`
	// Replace the schema of the body with one inferred from the example, for
	// untyped bodies (google.protobuf.Struct, google.api.HttpBody, bytes...).
	// The schema is added to the components as `<operation_id>Response` (or
	// `Request`). The example itself is not written, each property of the
	// schema gets a sample value instead. Requires a JSON content type.
	InferSchema   bool `protobuf:"varint,3,opt,name=infer_schema,json=inferSchema,proto3" json:"infer_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_pckt_openapi_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_pckt_openapi_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Example) GetSource() isExample_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Example) GetValue() string {
	if x != nil {
		if x, ok := x.Source.(*Example_Value); ok {
			return x.Value
		}
	}
	return ""
}

func (x *Example) GetFile() string {
	if x != nil {
		if x, ok := x.Source.(*Example_File); ok {
			return x.File
		}
	}
	return ""
}

func (x *Example) GetInferSchema() bool {
	if x != nil {
		return x.InferSchema
	}
	return false
}

func (x *Example) SetValue(v string) {
	x.Source = &Example_Value{v}
}

func (x *Example) SetFile(v string) {
	x.Source = &Example_File{v}
}

func (x *Example) SetInferSchema(v bool) {
	x.InferSchema = v
}

func (x *Example) HasSource() bool {
	if x == nil {
		return false
	}
	return x.Source != nil
}

func (x *Example) HasValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.Source.(*Example_Value)
	return ok
}

func (x *Example) HasFile() bool {
	if x == nil {
		return false
	}
	_, ok := x.Source.(*Example_File)
	return ok
}

func (x *Example) ClearSource() {
	x.Source = nil
}

func (x *Example) ClearValue() {
	if _, ok := x.Source.(*Example_Value); ok {
		x.Source = nil
	}
}

func (x *Example) ClearFile() {
	if _, ok := x.Source.(*Example_File); ok {
		x.Source = nil
	}
}

const Example_Source_not_set_case case_Example_Source = 0
const Example_Value_case case_Example_Source = 1
const Example_File_case case_Example_Source = 2

func (x *Example) WhichSource() case_Example_Source {
	if x == nil {
		return Example_Source_not_set_case
	}
	switch x.Source.(type) {
	case *Example_Value:
		return Example_Value_case
	case *Example_File:
		return Example_File_case
	default:
		return Example_Source_not_set_case
	}
}

type Example_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof Source:
	// Inline value, convenient for small examples
	Value *string
	// Path of a file holding the example, relative to the `examples_dir`
	// plugin option; it cannot point outside of that directory
	File *string
	// -- end of Source
	// Replace the schema of the body with one inferred from the example, for
	// untyped bodies (google.protobuf.Struct, google.api.HttpBody, bytes...).
	// The schema is added to the components as `<operation_id>Response` (or
	// `Request`). The example itself is not written, each property of the
	// schema gets a sample value instead. Requires a JSON content type.
	InferSchema bool
}

func (b0 Example_builder) Build() *Example {
	m0 := &Example{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		x.Source = &Example_Value{*b.Value}
	}
	if b.File != nil {
		x.Source = &Example_File{*b.File}
	}
	x.InferSchema = b.InferSchema
	return m0
}

type case_Example_Source protoreflect.FieldNumber

func (x case_Example_Source) String() string {
	md := file_pckt_openapi_options_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isExample_Source interface {
	isExample_Source()
}

type Example_Value struct {
	// Inline value, convenient for small examples
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type Example_File struct {
	// Path of a file holding the example, relative to the `examples_dir`
	// plugin option; it cannot point outside of that directory
	File string `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*Example_Value) isExample_Source() {}

func (*Example_File) isExample_Source() {}

type ExternalDocs struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalDocs) Reset() {
	*x = ExternalDocs{}
	mi := &file_pckt_openapi_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalDocs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalDocs) ProtoMessage() {}

func (x *ExternalDocs) ProtoReflect() protoreflect.Message {
	mi := &file_pckt_openapi_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExternalDocs) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExternalDocs) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExternalDocs) SetDescription(v string) {
	x.Description = v
}

func (x *ExternalDocs) SetUrl(v string) {
	x.Url = v
}

type ExternalDocs_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Description string
	Url         string
}

func (b0 ExternalDocs_builder) Build() *ExternalDocs {
	m0 := &ExternalDocs{}
	b, x := &b0, m0
	_, _ = b, x
	x.Description = b.Description
	x.Url = b.Url
	return m0
}

type TagOptions struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Tag name, defaults to the service name
	Name          string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExternalDocs  *ExternalDocs `protobuf:"bytes,3,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagOptions) Reset() {
	*x = TagOptions{}
	mi := &file_pckt_openapi_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagOptions) ProtoMessage() {}

func (x *TagOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pckt_openapi_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TagOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagOptions) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *TagOptions) SetName(v string) {
	x.Name = v
}

func (x *TagOptions) SetExternalDocs(v *ExternalDocs) {
	x.ExternalDocs = v
}

func (x *TagOptions) HasExternalDocs() bool {
	if x == nil {
		return false
	}
	return x.ExternalDocs != nil
}

func (x *TagOptions) ClearExternalDocs() {
	x.ExternalDocs = nil
}

type TagOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Tag name, defaults to the service name
	Name         string
	ExternalDocs *ExternalDocs
}

func (b0 TagOptions_builder) Build() *TagOptions {
	m0 := &TagOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.ExternalDocs = b.ExternalDocs
	return m0
}

var File_pckt_openapi_options_proto protoreflect.FileDescriptor

const file_pckt_openapi_options_proto_rawDesc = "" +
	"\n" +
	"\x1apckt/openapi/options.proto\x12\fpckt.openapi\x1a\x1cgoogle/protobuf/struct.proto\"\x84\x06\n" +
	"\fFieldOptions\x12\x18\n" +
	"\aexample\x18\x02 \x01(\tR\aexample\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.pckt.openapi.FieldTypeR\x04type\x121\n" +
	"\x06format\x18\x04 \x01(\x0e2\x19.pckt.openapi.FieldFormatR\x06format\x12\x18\n" +
	"\apattern\x18\x05 \x01(\tR\apattern\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x06 \x01(\bR\n" +
	"deprecated\x12\x16\n" +
	"\x06hidden\x18\a \x01(\bR\x06hidden\x12\x1a\n" +
	"\brequired\x18\b \x01(\bR\brequired\x12\x1b\n" +
	"\tread_only\x18\t \x01(\bR\breadOnly\x12\x1d\n" +
	"\n" +
	"write_only\x18\n" +
	" \x01(\bR\twriteOnly\x12\x1d\n" +
	"\aminimum\x18\v \x01(\x01H\x00R\aminimum\x88\x01\x01\x12\x1d\n" +
	"\amaximum\x18\f \x01(\x01H\x01R\amaximum\x88\x01\x01\x12\"\n" +
	"\n" +
	"min_length\x18\r \x01(\x04H\x02R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x0e \x01(\x04H\x03R\tmaxLength\x88\x01\x01\x12 \n" +
	"\tmin_items\x18\x0f \x01(\x04H\x04R\bminItems\x88\x01\x01\x12 \n" +
	"\tmax_items\x18\x10 \x01(\x04H\x05R\bmaxItems\x88\x01\x01\x12J\n" +
	"\n" +
	"extensions\x18\x11 \x03(\v2*.pckt.openapi.FieldOptions.ExtensionsEntryR\n" +
	"extensions\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_minimumB\n" +
	"\n" +
	"\b_maximumB\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_lengthB\f\n" +
	"\n" +
	"_min_itemsB\f\n" +
	"\n" +
	"_max_itemsJ\x04\b\x01\x10\x02R\vdescription\"\xdb\x02\n" +
	"\rSchemaOptions\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.pckt.openapi.FieldTypeR\x04type\x12\x16\n" +
	"\x06hidden\x18\x04 \x01(\bR\x06hidden\x12\x18\n" +
	"\aexample\x18\x05 \x01(\tR\aexample\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x06 \x01(\bR\n" +
	"deprecated\x12K\n" +
	"\n" +
	"extensions\x18\a \x03(\v2+.pckt.openapi.SchemaOptions.ExtensionsEntryR\n" +
	"extensions\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01J\x04\b\x02\x10\x03R\vdescription\"\xbd\x04\n" +
	"\x10OperationOptions\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12!\n" +
	"\foperation_id\x18\x04 \x01(\tR\voperationId\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x05 \x01(\bR\n" +
	"deprecated\x12\x16\n" +
	"\x06hidden\x18\x06 \x01(\bR\x06hidden\x12N\n" +
	"\n" +
	"extensions\x18\a \x03(\v2..pckt.openapi.OperationOptions.ExtensionsEntryR\n" +
	"extensions\x12>\n" +
	"\x0frequest_example\x18\b \x01(\v2\x15.pckt.openapi.ExampleR\x0erequestExample\x12@\n" +
	"\x10response_example\x18\t \x01(\v2\x15.pckt.openapi.ExampleR\x0fresponseExample\x120\n" +
	"\x14request_content_type\x18\n" +
	" \x01(\tR\x12requestContentType\x122\n" +
	"\x15response_content_type\x18\v \x01(\tR\x13responseContentType\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01J\x04\b\x02\x10\x03R\vdescription\"d\n" +
	"\aExample\x12\x16\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x12\x14\n" +
	"\x04file\x18\x02 \x01(\tH\x00R\x04file\x12!\n" +
	"\finfer_schema\x18\x03 \x01(\bR\vinferSchemaB\b\n" +
	"\x06source\"B\n" +
	"\fExternalDocs\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"t\n" +
	"\n" +
	"TagOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\rexternal_docs\x18\x03 \x01(\v2\x1a.pckt.openapi.ExternalDocsR\fexternalDocsJ\x04\b\x02\x10\x03R\vdescription*\xad\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FIELD_TYPE_FLOAT\x10\x01\x12\x15\n" +
	"\x11FIELD_TYPE_DOUBLE\x10\x02\x12\x14\n" +
	"\x10FIELD_TYPE_INT32\x10\x03\x12\x14\n" +
	"\x10FIELD_TYPE_INT64\x10\x04\x12\x14\n" +
	"\x10FIELD_TYPE_ARRAY\x10\x05\x12\x15\n" +
	"\x11FIELD_TYPE_OBJECT\x10\x06*\xba\x04\n" +
	"\vFieldFormat\x12\x1c\n" +
	"\x18FIELD_FORMAT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FIELD_FORMAT_DATE_TIME\x10\x01\x12\x15\n" +
	"\x11FIELD_FORMAT_TIME\x10\x02\x12\x15\n" +
	"\x11FIELD_FORMAT_DATE\x10\x03\x12\x19\n" +
	"\x15FIELD_FORMAT_DURATION\x10\x04\x12\x16\n" +
	"\x12FIELD_FORMAT_EMAIL\x10d\x12\x1a\n" +
	"\x16FIELD_FORMAT_IDN_EMAIL\x10e\x12\x1a\n" +
	"\x15FIELD_FORMAT_HOSTNAME\x10\xc8\x01\x12\x1e\n" +
	"\x19FIELD_FORMAT_IDN_HOSTNAME\x10\xc9\x01\x12\x16\n" +
	"\x11FIELD_FORMAT_IPV4\x10\xac\x02\x12\x16\n" +
	"\x11FIELD_FORMAT_IPV6\x10\xad\x02\x12\x16\n" +
	"\x11FIELD_FORMAT_UUID\x10\x90\x03\x12\x15\n" +
	"\x10FIELD_FORMAT_URI\x10\x91\x03\x12\x1f\n" +
	"\x1aFIELD_FORMAT_URI_REFERENCE\x10\x92\x03\x12\x15\n" +
	"\x10FIELD_FORMAT_IRI\x10\x93\x03\x12\x1f\n" +
	"\x1aFIELD_FORMAT_IRI_REFERENCE\x10\x94\x03\x12\x1e\n" +
	"\x19FIELD_FORMAT_URI_TEMPLATE\x10\xf4\x03\x12\x1e\n" +
	"\x19FIELD_FORMAT_JSON_POINTER\x10\xd8\x04\x12'\n" +
	"\"FIELD_FORMAT_RELATIVE_JSON_POINTER\x10\xd9\x04\x12\x17\n" +
	"\x12FIELD_FORMAT_REGEX\x10\xbc\x05B/Z-github.com/pckt-sh/openapi/proto/pckt/openapib\x06proto3"

var file_pckt_openapi_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pckt_openapi_options_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pckt_openapi_options_proto_goTypes = []any{
	(FieldType)(0),           // 0: pckt.openapi.FieldType
	(FieldFormat)(0),         // 1: pckt.openapi.FieldFormat
	(*FieldOptions)(nil),     // 2: pckt.openapi.FieldOptions
	(*SchemaOptions)(nil),    // 3: pckt.openapi.SchemaOptions
	(*OperationOptions)(nil), // 4: pckt.openapi.OperationOptions
	(*Example)(nil),          // 5: pckt.openapi.Example
	(*ExternalDocs)(nil),     // 6: pckt.openapi.ExternalDocs
	(*TagOptions)(nil),       // 7: pckt.openapi.TagOptions
	nil,                      // 8: pckt.openapi.FieldOptions.ExtensionsEntry
	nil,                      // 9: pckt.openapi.SchemaOptions.ExtensionsEntry
	nil,                      // 10: pckt.openapi.OperationOptions.ExtensionsEntry
	(*structpb.Value)(nil),   // 11: google.protobuf.Value
}
var file_pckt_openapi_options_proto_depIdxs = []int32{
	0,  // 0: pckt.openapi.FieldOptions.type:type_name -> pckt.openapi.FieldType
	1,  // 1: pckt.openapi.FieldOptions.format:type_name -> pckt.openapi.FieldFormat
	8,  // 2: pckt.openapi.FieldOptions.extensions:type_name -> pckt.openapi.FieldOptions.ExtensionsEntry
	0,  // 3: pckt.openapi.SchemaOptions.type:type_name -> pckt.openapi.FieldType
	9,  // 4: pckt.openapi.SchemaOptions.extensions:type_name -> pckt.openapi.SchemaOptions.ExtensionsEntry
	10, // 5: pckt.openapi.OperationOptions.extensions:type_name -> pckt.openapi.OperationOptions.ExtensionsEntry
	5,  // 6: pckt.openapi.OperationOptions.request_example:type_name -> pckt.openapi.Example
	5,  // 7: pckt.openapi.OperationOptions.response_example:type_name -> pckt.openapi.Example
	6,  // 8: pckt.openapi.TagOptions.external_docs:type_name -> pckt.openapi.ExternalDocs
	11, // 9: pckt.openapi.FieldOptions.ExtensionsEntry.value:type_name -> google.protobuf.Value
	11, // 10: pckt.openapi.SchemaOptions.ExtensionsEntry.value:type_name -> google.protobuf.Value
	11, // 11: pckt.openapi.OperationOptions.ExtensionsEntry.value:type_name -> google.protobuf.Value
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pckt_openapi_options_proto_init() }
func file_pckt_openapi_options_proto_init() {
	if File_pckt_openapi_options_proto != nil {
		return
	}
	file_pckt_openapi_options_proto_msgTypes[0].OneofWrappers = []any{}
	file_pckt_openapi_options_proto_msgTypes[3].OneofWrappers = []any{
		(*Example_Value)(nil),
		(*Example_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pckt_openapi_options_proto_rawDesc), len(file_pckt_openapi_options_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pckt_openapi_options_proto_goTypes,
		DependencyIndexes: file_pckt_openapi_options_proto_depIdxs,
		EnumInfos:         file_pckt_openapi_options_proto_enumTypes,
		MessageInfos:      file_pckt_openapi_options_proto_msgTypes,
	}.Build()
	File_pckt_openapi_options_proto = out.File
	file_pckt_openapi_options_proto_goTypes = nil
	file_pckt_openapi_options_proto_depIdxs = nil
}
